version: '3'
services:
  grafana:
    image: grafana/grafana:7.5.5
    container_name: grafana
    restart: always
    ports:
      - '3000:3000'
  e2e:
    image: cypress
    build: ./e2e
    container_name: cypress
    depends_on:
      - grafana
    environment:
      - CYPRESS_baseUrl=http://grafana:3000
    command: npx cypress run
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.json:/app/cypress.json
