version: '3.7'

services:
  grafana:
    image: grafana/grafana:8.0.3
    container_name: grafana-infinity-datasource
    ports:
      - '80:3000'
    volumes:
      - ./:/var/lib/grafana/plugins/grafana-infinity-datasource
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=production
      - GF_LOG_LEVEL=debug
      - GF_DATAPROXY_LOGGING=true
      - GF_INSTALL_PLUGINS=https://github.com/yesoreyeram/grafana-infinity-datasource/releases/download/v0.7.2/yesoreyeram-infinity-datasource-0.7.2.zip;yesoreyeram-infinity-datasource
