version: '3.7'

services:
  nginx:
    container_name: nginx
    image: nginx:1.19.10
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./instances/app.grafana.online/certs:/etc/certs/app.grafana.online/
      - ./instances/grafana.sriramajeyam.com/certs:/etc/certs/grafana.sriramajeyam.com/
  app_grafana_online:
    image: grafana/grafana:8.0.3
    user: '$UID:$GID'
    container_name: grafana-infinity-datasource
    volumes:
      - ./instances/app.grafana.online/data:/var/lib/grafana
      - ./instances/app.grafana.online/config/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./instances/app.grafana.online/config/config.ini:/etc/grafana/grafana.ini
    environment:
      - TERM=linux
      - GF_INSTALL_PLUGINS=https://github.com/yesoreyeram/grafana-infinity-datasource/releases/download/v0.7.3/yesoreyeram-infinity-datasource-0.7.3.zip;yesoreyeram-infinity-datasource
  grafana_sriramajeyam_com:
    image: grafana/grafana:8.0.3
    user: '$UID:$GID'
    container_name: grafana-infinity-datasource
    volumes:
      - ./instances/grafana.sriramajeyam.com/data:/var/lib/grafana
      - ./instances/grafana.sriramajeyam.com/config/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./instances/grafana.sriramajeyam.com/config/config.ini:/etc/grafana/grafana.ini
    environment:
      - TERM=linux
      - GF_INSTALL_PLUGINS=https://github.com/yesoreyeram/grafana-infinity-datasource/releases/download/v0.7.3/yesoreyeram-infinity-datasource-0.7.3.zip;yesoreyeram-infinity-datasource
