version: '3.7'

services:
  grafana:
    image: grafana/grafana:8.0.3
    container_name: grafana-infinity-datasource
    ports:
      - '80:3000'
    volumes:
      - ./data:/var/lib/grafana
      - ./config/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./config/config.ini:/var/lib/grafana/config.ini
    environment:
      - TERM=linux
      - GF_INSTALL_PLUGINS=https://github.com/yesoreyeram/grafana-infinity-datasource/releases/download/v0.7.2/yesoreyeram-infinity-datasource-0.7.2.zip;yesoreyeram-infinity-datasource
