name: Pull Requests
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS  }}
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.25.0
          inlineScript: |
            az deployment sub create --name infinity-deploy --location eastus --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --template-file ./try/arm-templates/infra.json --parameters @try/arm-templates/infra.parameters.json --parameters resourceGroupName=grafana-infinity-datasource
      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          region: eastus
          template: try/arm-templates/infra.json
          parameters: try/arm-templates/infra.parameters.json resourceGroupName=grafana-infinity-datasource
